language:
    node_js
node_js:
    - 0.8
notifications:
    irc: "irc.freenode.org#generator-travis-ci"
addons:
    sauce_connect:
        username: "wnr-hawker"
        access_key: "a5557696-e556-47d6-afad-f661d124b12a"
before_script:
    # install dependencies
    - gem update --system
    - gem install compass
    - npm install -g grunt-cli bower
script:
    # We want to gate on passing tests and a successful build
    - bower install
    - grunt test:sauce
